export type LangOption = { code: string; name: string; native: string };

export const LANGUAGES: LangOption[] = [
  { code: "en-US", name: "English", native: "English" },
  { code: "bn-BD", name: "Bengali", native: "বাংলা" },
  { code: "hi-IN", name: "Hindi", native: "हिन्दी" },
  { code: "ur-PK", name: "Urdu", native: "اردو" },
  { code: "ar-SA", name: "Arabic", native: "العربية" },
  { code: "fa-IR", name: "Persian", native: "فارسی" },
  { code: "tr-TR", name: "Turkish", native: "Türkçe" },
  { code: "es-ES", name: "Spanish", native: "Español" },
  { code: "pt-BR", name: "Portuguese (Brazil)", native: "Português" },
  { code: "fr-FR", name: "French", native: "Français" },
  { code: "de-DE", name: "German", native: "Deutsch" },
  { code: "it-IT", name: "Italian", native: "Italiano" },
  { code: "nl-NL", name: "Dutch", native: "Nederlands" },
  { code: "sv-SE", name: "Swedish", native: "Svenska" },
  { code: "pl-PL", name: "Polish", native: "Polski" },
  { code: "ru-RU", name: "Russian", native: "Русский" },
  { code: "uk-UA", name: "Ukrainian", native: "Українська" },
  { code: "el-GR", name: "Greek", native: "Ελληνικά" },
  { code: "he-IL", name: "Hebrew", native: "עברית" },
  { code: "zh-CN", name: "Chinese (Mandarin)", native: "中文" },
  { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
  { code: "ja-JP", name: "Japanese", native: "日本語" },
  { code: "ko-KR", name: "Korean", native: "한국어" },
  { code: "vi-VN", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "th-TH", name: "Thai", native: "ไทย" },
  { code: "id-ID", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ms-MY", name: "Malay", native: "Bahasa Melayu" },
  { code: "fil-PH", name: "Filipino", native: "Filipino" },
  { code: "ta-IN", name: "Tamil", native: "தமிழ்" },
  { code: "te-IN", name: "Telugu", native: "తెలుగు" },
  { code: "ml-IN", name: "Malayalam", native: "മലയാളം" },
  { code: "kn-IN", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "mr-IN", name: "Marathi", native: "मराठी" },
  { code: "gu-IN", name: "Gujarati", native: "ગુજરાતી" },
  { code: "pa-IN", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ne-NP", name: "Nepali", native: "नेपाली" },
  { code: "si-LK", name: "Sinhala", native: "සිංහල" },
  { code: "my-MM", name: "Burmese", native: "မြန်မာ" },
  { code: "km-KH", name: "Khmer", native: "ខ្មែរ" },
  { code: "sw-KE", name: "Swahili", native: "Kiswahili" },
  { code: "am-ET", name: "Amharic", native: "አማርኛ" },
  { code: "af-ZA", name: "Afrikaans", native: "Afrikaans" },
  { code: "zu-ZA", name: "Zulu", native: "isiZulu" },
  { code: "ha-NG", name: "Hausa", native: "Hausa" },
  { code: "yo-NG", name: "Yoruba", native: "Yorùbá" },
  { code: "ig-NG", name: "Igbo", native: "Igbo" },
  { code: "no-NO", name: "Norwegian", native: "Norsk" },
  { code: "da-DK", name: "Danish", native: "Dansk" },
  { code: "fi-FI", name: "Finnish", native: "Suomi" },
  { code: "cs-CZ", name: "Czech", native: "Čeština" },
  { code: "sk-SK", name: "Slovak", native: "Slovenčina" },
  { code: "hu-HU", name: "Hungarian", native: "Magyar" },
  { code: "ro-RO", name: "Romanian", native: "Română" },
  { code: "bg-BG", name: "Bulgarian", native: "Български" },
  { code: "hr-HR", name: "Croatian", native: "Hrvatski" },
  { code: "sr-RS", name: "Serbian", native: "Српски" },
  { code: "sl-SI", name: "Slovenian", native: "Slovenščina" },
  { code: "lt-LT", name: "Lithuanian", native: "Lietuvių" },
  { code: "lv-LV", name: "Latvian", native: "Latviešu" },
  { code: "et-EE", name: "Estonian", native: "Eesti" },
  { code: "is-IS", name: "Icelandic", native: "Íslenska" },
  { code: "ga-IE", name: "Irish", native: "Gaeilge" },
  { code: "cy-GB", name: "Welsh", native: "Cymraeg" },
  { code: "ca-ES", name: "Catalan", native: "Català" },
  { code: "eu-ES", name: "Basque", native: "Euskara" },
  { code: "gl-ES", name: "Galician", native: "Galego" },
  { code: "ka-GE", name: "Georgian", native: "ქართული" },
  { code: "hy-AM", name: "Armenian", native: "Հայերեն" },
  { code: "az-AZ", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "kk-KZ", name: "Kazakh", native: "Қазақ" },
  { code: "uz-UZ", name: "Uzbek", native: "Oʻzbek" },
  { code: "mn-MN", name: "Mongolian", native: "Монгол" },
  { code: "lo-LA", name: "Lao", native: "ລາວ" },
  { code: "pt-PT", name: "Portuguese (Portugal)", native: "Português (PT)" },
  { code: "es-MX", name: "Spanish (Mexico)", native: "Español (MX)" },
  { code: "en-GB", name: "English (UK)", native: "English (UK)" },
];

export const findLanguage = (code: string) =>
  LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
